import { Bubbler_One } from 'next/font/google';
import './globals.css';

const bubbler = Bubbler_One({
  subsets: ['latin'],
  display: 'swap',
  weight: '400',
});

export const metadata = {
  title: 'Balkana Home Page',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={bubbler.className}>{children}</body>
    </html>
  );
}
